### PR TITLE
Fix: Make the Navbar in the frontend Responsive

### PR DESCRIPTION
**Pull request by harrisonJones12**
In this PR I have made the Navbar look cleaner at 1051px width and removed a redundant "Log in button".
Screen Shot 2023-12-04 at 10 36 05 PM
Screen Shot 2023-12-04 at 10 35 47 PM

Issue link: https://github.com/1Shubham7/code-buddy/issues/22

### CODE REVIEW

**Comment by 1Shubham7** [comment]
Hey @harrisonJones12, thanks for your contribution. Let's merge it.

**Comment by 1Shubham7** [comment]
Would you want to add text in the image section? we can have a typing text there.

> In this PR I have made the Navbar look cleaner at 1051px width and removed a redundant "Log in button". Screen Shot 2023-12-04 at 10 36 05 PM Screen Shot 2023-12-04 at 10 35 47 PM
> 
> Issue link: #22

**Comment by harrisonJones12** [comment]
> Hey @harrisonJones12, thanks for your contribution. Let's merge it.



> Hey @harrisonJones12, thanks for your contribution. Let's merge it.

Yeah, no problem.

**Comment by harrisonJones12** [comment]
> Would you want to add text in the image section? we can have a typing text there.
> 
> > In this PR I have made the Navbar look cleaner at 1051px width and removed a redundant "Log in button". Screen Shot 2023-12-04 at 10 36 05 PM Screen Shot 2023-12-04 at 10 35 47 PM
> > Issue link: #22

Oh yeah, I can do that.

**Comment by 1Shubham7** [comment]
https://github.com/1Shubham7/code-buddy/issues/29 here's the issue. Comment on that so that I can assign  it to you.

**Pull request merged**
