### PR TITLE
Update Modern Buttons

### LINKED ISSUE #43: Add Modern buttons and Suitable font filter section
This buttons and and their font style is not suitalble for webapp

Capture

### PR DESCRIPTION
**Pull request by AaadityaG**
Close #43

https://github.com/1Shubham7/code-buddy/assets/114663382/8386c90a-da44-4053-8504-1d777818dbc2

### CODE REVIEW

**Comment by AaadityaG** [comment]
Brother where should I execute "npm run bulid" before pushing in frontend folder or code-buddy.. I have used in frontend folder but its not working for deployment, should I try second one..

**Comment by AaadityaG** [comment]
Bro Any Idea why deployment is failing

**Comment by 1Shubham7** [comment]
no, issues are with backend integrations with frontend that's why at checks might be failing. why have you changed soo many files, did you install some dependencies ?

**Comment by AaadityaG** [comment]
Yes I executed "npm run build"

**Comment by AaadityaG** [comment]
what should I do to push the changes only

**Comment by 1Shubham7** [comment]
did you install dependencies?

**Comment by 1Shubham7** [comment]
I checked your commits, you haven't install dependencies, you first commit is perfect. Can you make another PR where you only make changes and push them. You don;t have to do `npm run build`. Netlify takes care of that.

**Pull request closed without merging**
