### PR TITLE
responsiveness added to footer

### PR DESCRIPTION
**Pull request by Sumandalai**

### CODE REVIEW

**Review by 1Shubham7 — COMMENTED** [review]
This woks fine.

**Comment by 1Shubham7** [comment]
Thanks @Sumandalai for your contribution. It really means a lot. Please do contribute more, we can work on the me section's responsiveness. Actually I am not very good with responsiveness.

**Comment by Sumandalai** [comment]
thank you @1Shubham7.I'm glad to hear that my contribution was valuable. I'm genuinely excited to contribute more and collaborate on enhancing the responsiveness of the "Me" section.

**Comment by 1Shubham7** [comment]
That's great, let's create another issue. 
https://github.com/1Shubham7/code-buddy/issues/37

Here's the link, comment down there so that I can assign you the issue.

**Pull request merged**
