### PR TITLE
Fixed Issue #47 - Added Scroll-Reveal effect to the website

### PR DESCRIPTION
**Pull request by sambitsingha**
### Added a new effect - Scroll Reveal 
The website , when scrolled , reveals it's elements one by one in a systematic way. This can be seen by continous scrolling throughout the site.

### How to add classes to this effect !!
```
sr.reveal(".navbar,.top-text,.about-text,.search-bar-holder,.how", {
			// Configure ScrollReveal options here
			reset: true,
			delay: 200,
			distance: "40px",
			origin: "top",
			duration: 2000,
		});
```
Here , the rules of the effect are specified such as delay, distance , origin  and so on. We have to mention the class names inside the `sr.reveal(" {enter classname} ")`  part. 

For customisation of the rules, simply copy this section and paste in the next line and modify the rules according , along with different classnames ( It is reccommeded not to have different rules for a same element )

```
		sr.reveal(".copyright", {
			// Configure ScrollReveal options here
			reset: true,
			delay: 400,
			distance: "40px",
			origin: "bottom",
			duration: 2000,
		});
```
Here , the rules have been modifed for a different class `.copyright` and modifed the origin from `top` to `bottom`
Similar customistation can also be done to any elements required.

**The classname are also required to mention in the return tag of the `ScrollRevealComponent.js` file**
```
return (
		<div>
			<div className="navbar"></div>
			<div className="top-text"></div>
			<div className="list"></div>
		</div>
	);
```
### A clip of the Scroll Reveal effect

https://github.com/1Shubham7/code-buddy/assets/110420002/aae3175e-c0f9-44a7-b4b0-1ff301f97244

#### Added a feature. I am open to any changes if needed. Thank You :)

### CODE REVIEW

**Comment by sambitsingha** [comment]
@1Shubham7  hey I dont know why the checks have failed. Please see to it. From my side , **I did my part** :)

**Comment by 1Shubham7** [comment]
That's a lot of work @sambitsingha . Thanks a lot for that. Did you install any package for this?

**Comment by sambitsingha** [comment]
@1Shubham7  I added a CDN link , customised it according to the site .

**Comment by 1Shubham7** [comment]
I mean you have changed the package.lock file. Where have you added the CDN link?

**Comment by sambitsingha** [comment]
Index.html

**Comment by 1Shubham7** [comment]
got it, I think we should not change the package.lock file. Can you this, commit those individual files rather than `git add .` you can do `git add [FILE NAME]` and then commit it. Or you can go to individual files in GitHub and edit them then simply paste the code there. We will have to create a new PR for that.

**Comment by sambitsingha** [comment]
@1Shubham7  Actually i don't why , but the `package-lock.json` file seem to be updated when in used `npm install`

**Comment by 1Shubham7** [comment]
Yes, it may. Simply don't push it. It may be happening since you are using latest versions of dependencies and the project may have bit older ones.

**Comment by sambitsingha** [comment]
So then , let me copy the version of the `package-lock.json` file from the main branch and push that. The other files are ok ig.

**Comment by 1Shubham7** [comment]
yup, that should work fine. You can then create a new PR.

**Comment by sambitsingha** [comment]
Is a new PR needed .. i dont know because it is showing that it has been modified in this PR only. You tell

**Comment by 1Shubham7** [comment]
ok that should work fine, I will make changes if anything goes wrong. Thanks a lot @sambitsingha your for contribution. It really means a lot. Do contribute more make submitting issues and solving them.

**Pull request merged**
